# Generated by Django 6.0.1 on 2026-01-24 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionapplication',
            options={'verbose_name': 'Competition Application', 'verbose_name_plural': 'Competition Applications'},
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.RenameField(
            model_name='competitionapplication',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='email',
            new_name='au_email',
        ),
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone_num',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid US phone number.', regex='^\\+?1?\\D*(\\d\\D*){10}$')]),
        ),
    ]
