# Generated by Django 6.0.1 on 2026-01-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_competitionapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionapplication',
            name='competition_type',
            field=models.CharField(choices=[('college_fed', 'College Fed'), ('cfa', 'CFA Competition'), ('game', 'Game Competition')], default='legacy', max_length=50),
            preserve_default=False,
        ),
    ]
