# Generated by Django 6.0.1 on 2026-01-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_competitionapplication_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionapplication',
            name='competition_type',
            field=models.CharField(choices=[('college_fed', 'College Fed'), ('cfa', 'CFA'), ('game', 'Game')], max_length=50),
        ),
        migrations.AlterField(
            model_name='competitionapplication',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
