# Generated by Django 6.0.1 on 2026-02-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_competitionapplication_competition_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Stock ticker symbol (e.g., AAPL, MSFT, SPY)', max_length=10, unique=True)),
                ('shares', models.DecimalField(decimal_places=4, help_text='Number of shares owned', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from portfolio without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Holding',
                'verbose_name_plural': 'Portfolio Holdings',
                'ordering': ['ticker'],
            },
        ),
    ]
